return {
  ensure_installed = {
    "lua-language-server",
    "html-lsp",
    "prettier",
    "stylua",
    "eslint_d",
    "ansible-language-server",
    "ansible-lint",
    "bash-language-server",
    "cfn-lint",
    "docker-compose-language-service",
    "dockerfile-language-server",
    "hadolint",
    -- "groovy-language-server",
    "helm-ls",
    -- "htmlbeautifier",
    "jq",
    -- "jq-lsp",
    "json-lsp",
    "jsonlint",
    "markdownlint",
    "marksman",
    -- "nginx-language-server",
    "pylint",
    "pyright",
    "black",
    "python-lsp-server",
    "shellcheck",
    "shfmt",
    "gopls",
    "goimports",
    "gofumpt",
    "golangci-lint",
    "gotests",
    "gomodifytags",
    "gotests",
    "debugpy",
    "iferr",
    "impl",
    "delve",
    "bash-debug-adapter",
    -- "shellharden",
    -- "snyk",
    -- "snyk-ls",
    -- "sql-formatter",
    -- "sqlfluff",
    -- "sqlls",
    "terraform-ls",
    "tflint",
    -- "trivy",
    "typescript-language-server",
    "xmlformatter",
    "vale",
    "yaml-language-server",
    "yamllint",
    "yq",
  },
}
