#!/bin/sh

if ! command -v vim >/dev/null 2>&1 || ! command -v vimtutor >/dev/null 2>&1; then
  echo "Warning, doesn't look like you have full Vim version."
fi

script_dir=$(CDPATH='' cd -- "$(dirname -- "$0")" && pwd)
ln -sf "$script_dir/.vimrc" "$HOME/.vimrc"
mkdir -p "$HOME/.vim/autoload"
ln -sf "$script_dir/.vim/autoload/plug.vim" "$HOME/.vim/autoload/plug.vim"
