#!/usr/bin/env bash

set -eu

[[ ${TEST_DOWNLOAD_FAIL:-0} == 0 ]] || exit 60
destination=
while [[ $# -gt 0 ]]; do
  if [[ $1 == -o || $1 == --output ]]; then
    [[ $# -ge 2 ]] || exit 61
    destination=$2
    shift 2
  else
    shift
  fi
done
[[ -n $destination ]]
cp "$TEST_DOWNLOAD_FILE" "$destination"
