#!/bin/bash

POD_PREFIXES=(
  "api"
  "disc-api"
  "transac-api"
  "web"
  "cdc"
  "search-indexing"
  "invhub-interaction-engine"
  "invhub-prompt-engine"
  "invhub-context-engine"
  "invhub-websearch"
  "copilot-interaction-engine"
  "copilot-prompt-engine"
  "copilot-context-engine"
  "copilot-websearch"
  "copilotv2"
  "copilot-data-adapter"
  "sail-data-agent"
  "eureka-workflows-registry"
  "workflow-canvas-ui"
  "workflow-manager"
  "webhook-service"
  "activity-release"
  "orchestrator-api"
  "workers-release"
)

TIMESTAMP=$(date "+%Y-%m-%d_%H-%M-%S")

LOG_DIR="${TIMESTAMP}_invhub_logs"
mkdir -p "$LOG_DIR"

SINCE_PARAM=""
if [ -n "$1" ]; then
  SINCE_PARAM="--since=$1"
fi

for PREFIX in "${POD_PREFIXES[@]}"; do
  PODS=$(kubectl get pods --no-headers -o custom-columns=":metadata.name" | grep "^$PREFIX")

  for POD in $PODS; do
    if [ -n "$POD" ]; then
      LOG_FILE="${LOG_DIR}/${TIMESTAMP}-${POD}.log"
      kubectl logs $SINCE_PARAM $POD >$LOG_FILE
      echo "Logs for $POD saved to $LOG_FILE"
    fi
  done
done
