#!/bin/bash
# Gendate generates the date in YYY-MM-DD format
# Can be called with arguments h and number to generate a markdown heading
# For example: 'gendate h 3' will generate '### 2023-03-29'

header=""
date=$(date +"%Y-%m-%d")

if [[ $# -eq 0 ]]; then
	echo "$date"
	exit 0
fi

if [[ $# -ne 2 || $1 != "h" || ! $2 =~ ^[1-6]$ ]]; then
	echo "Usage: gendate h 2 to generate with markdown heading ##" >&2
	exit 1
fi

for ((i = 0; i < 10#$2; i++)); do
	header+="#"
done
echo "$header $date"
