#!/usr/bin/env bash

set -euo pipefail

self=$(readlink -f -- "$0")
tool=${self##*/}
release=${self%/bin/*}
case $tool in
  kubectl) version=${KUBECTL_VERSION:-} ;;
  helm) version=${HELM_VERSION:-} ;;
  *) printf 'offline client: unsupported command: %s\n' "$tool" >&2; exit 2 ;;
esac

binary=$release/tools/bin/$tool
if [[ -n $version ]]; then
  [[ $version =~ ^v?[0-9]+([.][0-9]+){1,3}([0-9A-Za-z.+-]*[0-9A-Za-z])?$ ]] || {
    printf '%s: invalid version: %s\n' "$tool" "$version" >&2
    exit 2
  }
  binary=$binary-$version
fi
[[ -x $binary ]] || {
  printf '%s: version %s is not bundled in %s\n' "$tool" "${version:-default}" "$release" >&2
  exit 127
}
exec "$binary" "$@"
