#!/bin/bash

shopt -s nullglob

for directory in ./NSCO.Workload.*/; do
	target=${directory#./NSCO.Workload.}
	target=${target%/}
	if [[ -e $target ]]; then
		echo "Target already exists: $target" >&2
		exit 1
	fi
	mv -- "$directory" "$target"
done
